#:import start_page start_page
#:import on_game on_game
#: import record_db record_db
#: import overall_rank overall_rank
#: import player_detail player_detail


MainInterface:

<MainInterface>:

    start: start
    game: game
    record: record
    rank: rank
    detail: detail

    Record_db:
        id: record
    On_game:
        id: game
    Start_page:
        id: start
    Overall_rank:
        id: rank
    Player_detail:
        id: detail